In [1]:
import pandas as pd

In [3]:
d1 = pd.read_csv("/Users/surisettivamsikrishna/Desktop/updated3 3.csv")

In [4]:
d1

,Unnamed: 0.1,Unnamed: 0,Content ID,User ID,Type,Category,Unnamed: 6
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN
1,1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating,NaN
2,2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating,NaN
3,3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology,NaN
4,4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food,NaN
...,...,...,...,...,...,...,...
796,994,994,c54b49c4-b1f2-4641-8595-1cbd19937845,2ab641a8-6ad4-4d1a-8511-d87ff5346773,photo,science,NaN
797,996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology,NaN
798,997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism,NaN
799,998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture,NaN
800,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN

In [17]:
d1.drop(['Unnamed: 6'],axis=1)

,Unnamed: 0.1,Unnamed: 0,Content ID,User ID,Type,Category
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying
1,1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating
2,2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating
3,3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology
4,4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food
...,...,...,...,...,...,...
796,994,994,c54b49c4-b1f2-4641-8595-1cbd19937845,2ab641a8-6ad4-4d1a-8511-d87ff5346773,photo,science
797,996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology
798,997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism
799,998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture
800,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology

In [18]:
d1.head()

,Unnamed: 0.1,Unnamed: 0,Content ID,User ID,Type,Category,Unnamed: 6
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN
1,1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating,NaN
2,2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating,NaN
3,3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology,NaN
4,4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food,NaN

In [13]:
d2 = pd.read_csv("/Users/surisettivamsikrishna/Desktop/updated.csv")

In [14]:
d2

,Unnamed: 0.1,Unnamed: 0,Content ID,User ID,Type,Datetime
0,1,1,97522e57-d9ab-4bd6-97bf-c24d952602d2,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50
1,2,2,97522e57-d9ab-4bd6-97bf-c24d952602d2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51
2,3,3,97522e57-d9ab-4bd6-97bf-c24d952602d2,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58
3,4,4,97522e57-d9ab-4bd6-97bf-c24d952602d2,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01
4,5,5,97522e57-d9ab-4bd6-97bf-c24d952602d2,9b6d35f9-5e15-4cd0-a8d7-b1f3340e02c4,interested,2020-08-23 12:25:58
...,...,...,...,...,...,...
22529,25547,25547,75d6b589-7fae-4a6d-b0d0-752845150e56,b6d04982-1509-41ab-a700-b390d6cb4d02,worried,2020-10-31 04:50:14
22530,25548,25548,75d6b589-7fae-4a6d-b0d0-752845150e56,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48
22531,25549,25549,75d6b589-7fae-4a6d-b0d0-752845150e56,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02
22532,25551,25551,75d6b589-7fae-4a6d-b0d0-752845150e56,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31
22533,25552,25552,75d6b589-7fae-4a6d-b0d0-752845150e56,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11

In [25]:
d1.merge(d2,how='inner',on='Content ID')

,Unnamed: 0.1_x,Unnamed: 0_x,Content ID,User ID_x,Type_x,Category,Unnamed: 6,Unnamed: 0.1_y,Unnamed: 0_y,User ID_y,Type_y,Datetime
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,1,1,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50
1,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,2,2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51
2,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,3,3,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58
3,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,4,4,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01
4,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,5,5,9b6d35f9-5e15-4cd0-a8d7-b1f3340e02c4,interested,2020-08-23 12:25:58
...,...,...,...,...,...,...,...,...,...,...,...,...
18379,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25547,25547,b6d04982-1509-41ab-a700-b390d6cb4d02,worried,2020-10-31 04:50:14
18380,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25548,25548,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48
18381,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25549,25549,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02
18382,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25551,25551,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31
18383,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25552,25552,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11

In [31]:
d1.drop(columns=['Unnamed: 6'])

,Unnamed: 0.1,Unnamed: 0,Content ID,User ID,Type,Category
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying
1,1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating
2,2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating
3,3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology
4,4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food
...,...,...,...,...,...,...
796,994,994,c54b49c4-b1f2-4641-8595-1cbd19937845,2ab641a8-6ad4-4d1a-8511-d87ff5346773,photo,science
797,996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology
798,997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism
799,998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture
800,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology

In [33]:
d1.merge(d2,how='inner',on='Content ID')

,Unnamed: 0.1_x,Unnamed: 0_x,Content ID,User ID_x,Type_x,Category,Unnamed: 6,Unnamed: 0.1_y,Unnamed: 0_y,User ID_y,Type_y,Datetime
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,1,1,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50
1,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,2,2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51
2,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,3,3,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58
3,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,4,4,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01
4,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,NaN,5,5,9b6d35f9-5e15-4cd0-a8d7-b1f3340e02c4,interested,2020-08-23 12:25:58
...,...,...,...,...,...,...,...,...,...,...,...,...
18379,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25547,25547,b6d04982-1509-41ab-a700-b390d6cb4d02,worried,2020-10-31 04:50:14
18380,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25548,25548,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48
18381,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25549,25549,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02
18382,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25551,25551,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31
18383,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,NaN,25552,25552,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11

In [76]:
pd.value_counts(data['Datetime'])

KeyError: 'Datetime'

In [39]:
data = d1.drop(columns=['Unnamed: 6'])

In [40]:
data

,Unnamed: 0.1,Unnamed: 0,Content ID,User ID,Type,Category
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying
1,1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating
2,2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating
3,3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology
4,4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food
...,...,...,...,...,...,...
796,994,994,c54b49c4-b1f2-4641-8595-1cbd19937845,2ab641a8-6ad4-4d1a-8511-d87ff5346773,photo,science
797,996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology
798,997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism
799,998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture
800,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology

In [41]:
data.merge(d2,how='inner',on='Content ID')

,Unnamed: 0.1_x,Unnamed: 0_x,Content ID,User ID_x,Type_x,Category,Unnamed: 0.1_y,Unnamed: 0_y,User ID_y,Type_y,Datetime
0,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,1,1,5d454588-283d-459d-915d-c48a2cb4c27f,disgust,2020-11-07 09:43:50
1,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,2,2,92b87fa5-f271-43e0-af66-84fac21052e6,dislike,2021-06-17 12:22:51
2,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,3,3,163daa38-8b77-48c9-9af6-37a6c1447ac2,scared,2021-04-18 05:13:58
3,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,4,4,34e8add9-0206-47fd-a501-037b994650a2,disgust,2021-01-06 19:13:01
4,0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,5,5,9b6d35f9-5e15-4cd0-a8d7-b1f3340e02c4,interested,2020-08-23 12:25:58
...,...,...,...,...,...,...,...,...,...,...,...
18379,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,25547,25547,b6d04982-1509-41ab-a700-b390d6cb4d02,worried,2020-10-31 04:50:14
18380,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,25548,25548,80c9ce48-46f9-4f5e-b3ca-3b698fc2e949,dislike,2020-06-27 09:46:48
18381,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,25549,25549,2bd9c167-e06c-47c1-a978-3403d6724606,intrigued,2021-02-16 17:17:02
18382,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,25551,25551,5ffd8b51-164e-47e2-885e-8b8c46eb63ed,worried,2020-11-04 20:08:31
18383,999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,25552,25552,4edc3d1a-a7d9-4db6-89c3-f784d9954172,cherish,2021-01-04 04:55:11

In [60]:
data.to_csv(r"/Users/surisettivamsikrishna/Desktop/socialbuzz2.csv",index=False)

In [71]:
pd.value_counts(data['Category'])

Category
travel             60
science            55
fitness            54
animals            54
culture            54
technology         54
tennis             53
cooking            51
healthy eating     50
dogs               49
education          48
soccer             47
food               47
veganism           43
studying           41
public speaking    40
Studying            1
Name: count, dtype: int64

In [75]:
pd.value_counts(data['Datetime'])

KeyError: 'Datetime'